server {
    listen 80;
    listen [::]:80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    access_log /logs/ota_access.log combined;
    error_log /logs/ota_error.log warn;

    location / {
        try_files $uri $uri/ =404;
    }
}
